/**
 * Deterministic translator: one `DomainDocument` slice + one chosen
 * `FactorySignature` → one `FactoryCallSite`. The agent picks the
 * signature upstream via embedding-search over the catalog; this
 * function does ZERO matching. It just lowers domain fields onto the
 * factory's advertised param surface, field-by-field.
 *
 * The binding (which `DomainEntity` / `DomainPage[]` map to this
 * orbital) is the agent's explicit decision and is passed in. No name
 * matching, no scoring, no tie-breaks.
 *
 * Adding a new domain concept means:
 *   1. Add a field on `DomainEntity` / `DomainPage` / `DomainBehavior`
 *      (`packages/almadar-core/src/domain-language/types.ts`).
 *   2. Make sure at least one factory signature advertises a
 *      consuming knob (Phase 1.5 gate — generated by
 *      almadar-pattern-sync from `.orb`).
 *   3. Add one helper-fn row below that lowers the new field into
 *      `FactoryCallSiteParams`.
 *
 * If a binding field has no signature consumer, the translator emits
 * a typed warning and SKIPS the field — that's the loud signal the
 * field shouldn't have been admitted to the language.
 */

import type { EntityField } from '../../types/field.js';
import type { TraitReference } from '../../types/trait.js';
import type {
  DomainEntity,
  DomainField,
  DomainFieldDefault,
  DomainPage,
  DomainRuleOverlayEntry,
  FactoryCallSite,
  FactoryCallSiteParams,
  FactoryParamValue,
  FactorySignature,
  FactoryTraitSignature,
  OwnershipOverlayEntry,
  PresentationNavItem,
  PresentationOverlay,
  RuleOverlay,
  TraitOverlay,
  TraitOverlayEntry,
} from '../types.js';
import { DOMAIN_TO_SCHEMA_FIELD_TYPE } from '../types.js';

/**
 * The slice of `DomainDocument` that maps onto the chosen signature.
 * The agent assembles this when it picks the signature: it knows
 * which `DomainEntity` / `DomainPage[]` are this orbital's
 * responsibility.
 */
export interface TranslationBinding {
  /** The single domain entity this signature's orbital owns. */
  entity: DomainEntity;
  /** Pages from the domain doc that map to this orbital's pages. The
   *  translator pairs them with `signature.pages[]` by name. */
  pages?: ReadonlyArray<DomainPage>;
}

export interface TranslationWarning {
  /** Dotted path of the domain field that couldn't be lowered. */
  field: string;
  /** Human-readable reason. */
  reason: string;
}

export interface TranslationResult {
  callSite: FactoryCallSite;
  warnings: ReadonlyArray<TranslationWarning>;
}

export function translateDomainToParams(
  binding: TranslationBinding,
  signature: FactorySignature,
  presentation?: PresentationOverlay,
  ruleOverlay?: RuleOverlay,
  traitOverlay?: TraitOverlay,
  catalog?: ReadonlyArray<FactorySignature>,
): TranslationResult {
  const warnings: TranslationWarning[] = [];
  const params: FactoryCallSiteParams = {};

  applyEntityName(binding.entity, signature, params);
  applyEntityFields(binding.entity, signature, params, warnings);
  applyPersistence(binding.entity, signature, params, warnings);
  applyPagePaths(binding.pages ?? [], signature, params, warnings);
  applyPresentation(presentation, signature, params, warnings);
  applyTraitOverlay(traitOverlay, signature, params, warnings);
  applyRuleOverlay(ruleOverlay, signature, binding, catalog, params, warnings);

  return {
    callSite: {
      organism: signature.organism,
      orbital: signature.orbital,
      factoryPath: signature.factoryPath,
      params,
    },
    warnings,
  };
}

// ---------------------------------------------------------------------------
// Per-field lowering — one helper per row in the domain↔factory table.
// ---------------------------------------------------------------------------

function applyEntityName(
  entity: DomainEntity,
  signature: FactorySignature,
  params: FactoryCallSiteParams,
): void {
  if (signature.entities.length === 0) return;
  if (entity.name === signature.entities[0].name) return;
  params.entityName = entity.name;
}

function applyEntityFields(
  entity: DomainEntity,
  signature: FactorySignature,
  params: FactoryCallSiteParams,
  warnings: TranslationWarning[],
): void {
  if (signature.entities.length === 0) {
    if (entity.fields.length > 0) {
      warnings.push({
        field: `entity.${entity.name}.fields`,
        reason: 'factory signature does not advertise an entity surface',
      });
    }
    return;
  }
  const canonical = new Set(signature.entities[0].fields.map((f) => f.name));
  const extras: EntityField[] = [];
  for (const f of entity.fields) {
    if (canonical.has(f.name)) continue;
    const lowered = lowerField(f);
    if (lowered) extras.push(lowered);
  }
  if (extras.length > 0) params.entityFields = extras;
}

function applyPersistence(
  entity: DomainEntity,
  signature: FactorySignature,
  params: FactoryCallSiteParams,
  warnings: TranslationWarning[],
): void {
  if (!entity.persistence) return;
  if (signature.entities.length === 0) {
    warnings.push({
      field: `entity.${entity.name}.persistence`,
      reason: 'factory signature has no entity to apply persistence to',
    });
    return;
  }
  if (entity.persistence === signature.entities[0].persistence) return;
  params.persistence = entity.persistence;
}

function applyPagePaths(
  pages: ReadonlyArray<DomainPage>,
  signature: FactorySignature,
  params: FactoryCallSiteParams,
  warnings: TranslationWarning[],
): void {
  if (pages.length === 0) return;
  const sigPages = new Map(signature.pages.map((p) => [p.name, p]));
  const overrides: Record<string, string> = {};
  for (const p of pages) {
    const sig = sigPages.get(p.name);
    if (!sig) {
      warnings.push({
        field: `page.${p.name}.url`,
        reason: `factory signature has no page named "${p.name}"`,
      });
      continue;
    }
    if (sig.defaultPath !== p.url) overrides[p.name] = p.url;
  }
  if (Object.keys(overrides).length > 0) params.pagePaths = overrides;
}

function applyPresentation(
  overlay: PresentationOverlay | undefined,
  signature: FactorySignature,
  params: FactoryCallSiteParams,
  warnings: TranslationWarning[],
): void {
  if (!overlay?.navAdditions || overlay.navAdditions.length === 0) return;
  const target = signature.traits.find((t) =>
    t.overridableConfigKeys.includes('navItems'),
  );
  if (!target) {
    warnings.push({
      field: 'presentation.navAdditions',
      reason:
        'factory signature has no trait advertising a `navItems` config key',
    });
    return;
  }
  const existing = params.traitOverrides?.[target.name] ?? {};
  const existingConfig = existing.config ?? {};
  const items: ReadonlyArray<FactoryParamValue> = overlay.navAdditions.map(
    navItemToParamValue,
  );
  params.traitOverrides = {
    ...params.traitOverrides,
    [target.name]: {
      ...existing,
      config: { ...existingConfig, navItems: items },
    },
  };
}

// ---------------------------------------------------------------------------
// Phase 4 overlay rows
// ---------------------------------------------------------------------------

function applyTraitOverlay(
  overlay: TraitOverlay | undefined,
  signature: FactorySignature,
  params: FactoryCallSiteParams,
  warnings: TranslationWarning[],
): void {
  if (!overlay) return;
  const traitsByName = new Map(signature.traits.map((t) => [t.name, t]));
  for (const [traitName, entry] of Object.entries(overlay)) {
    const trait = traitsByName.get(traitName);
    if (!trait) {
      warnings.push({
        field: `traitOverlay.${traitName}`,
        reason: `factory signature has no trait named "${traitName}"`,
      });
      continue;
    }
    mergeTraitOverride(traitName, entry, trait, params, warnings);
  }
}

function mergeTraitOverride(
  traitName: string,
  entry: TraitOverlayEntry,
  trait: FactoryTraitSignature,
  params: FactoryCallSiteParams,
  warnings: TranslationWarning[],
): void {
  const advertised = new Set(trait.overridableConfigKeys);
  const existing = params.traitOverrides?.[traitName] ?? {};
  const existingConfig = existing.config ?? {};
  const mergedConfig: Record<string, FactoryParamValue> = { ...existingConfig };

  if (entry.config) {
    for (const [k, v] of Object.entries(entry.config)) {
      if (!advertised.has(k)) {
        warnings.push({
          field: `traitOverlay.${traitName}.config.${k}`,
          reason: `trait does not advertise config key "${k}" (overridableConfigKeys: [${trait.overridableConfigKeys.join(', ')}])`,
        });
        continue;
      }
      mergedConfig[k] = v;
    }
  }

  const next: FactoryCallSiteParams['traitOverrides'] extends infer T
    ? T extends Readonly<Record<string, infer V>>
      ? V
      : never
    : never = {
    ...existing,
    ...(Object.keys(mergedConfig).length > 0 ? { config: mergedConfig } : {}),
  };

  params.traitOverrides = {
    ...params.traitOverrides,
    [traitName]: next,
  };
}

function applyRuleOverlay(
  overlay: RuleOverlay | undefined,
  signature: FactorySignature,
  binding: TranslationBinding,
  catalog: ReadonlyArray<FactorySignature> | undefined,
  params: FactoryCallSiteParams,
  warnings: TranslationWarning[],
): void {
  if (!overlay) return;

  for (const rule of overlay.rules) {
    if (!ruleAppliesToBinding(rule, binding)) continue;
    if (!catalog) {
      warnings.push({
        field: `ruleOverlay.rules.${rule.id}`,
        reason: 'rule overlay supplied without a catalog — capability lookup requires one',
      });
      continue;
    }
    const match = findTraitByCapability(catalog, rule.capability);
    if (!match) {
      warnings.push({
        field: `ruleOverlay.rules.${rule.id}`,
        reason: `no trait in the catalog advertises capability "${rule.capability}"`,
      });
      continue;
    }
    appendRuleExtraTrait(rule, match, binding, params);
    if (rule.config) {
      threadRuleConfig(rule, match.trait, params, warnings);
    }
  }

  if (overlay.ownership) {
    for (const entry of overlay.ownership) {
      if (entry.entity !== binding.entity.name) continue;
      applyOwnership(entry, params, signature, catalog, warnings);
    }
  }
}

function ruleAppliesToBinding(
  rule: DomainRuleOverlayEntry,
  binding: TranslationBinding,
): boolean {
  if (rule.appliesTo.length === 0) return true;
  return rule.appliesTo.includes(binding.entity.name);
}

interface CapabilityMatch {
  signature: FactorySignature;
  trait: FactoryTraitSignature;
}

function findTraitByCapability(
  catalog: ReadonlyArray<FactorySignature>,
  capability: string,
): CapabilityMatch | undefined {
  // Deterministic order: catalog is sorted by (organism, orbital) at
  // emit time; first hit wins. No scoring, no tie-break heuristics.
  for (const sig of catalog) {
    for (const trait of sig.traits) {
      if (trait.capabilities.includes(capability)) {
        return { signature: sig, trait };
      }
    }
  }
  return undefined;
}

function appendRuleExtraTrait(
  rule: DomainRuleOverlayEntry,
  match: CapabilityMatch,
  binding: TranslationBinding,
  params: FactoryCallSiteParams,
): void {
  const fromPath = `std/behaviors/${match.signature.organism}`;
  const alias = organismToAlias(match.signature.organism);
  const ref: TraitReference = {
    from: fromPath,
    ref: `${alias}.traits.${match.trait.name}`,
    linkedEntity: binding.entity.name,
  };
  const existing = params.extraTraits ?? [];
  params.extraTraits = [...existing, ref];
}

/**
 * `std-row-access-control` → `RowAccess`,
 * `std-audit-capture` → `AuditCapture`, etc.
 * Strips `std-` prefix, splits on `-`, title-cases each segment.
 */
function organismToAlias(organism: string): string {
  const trimmed = organism.startsWith('std-') ? organism.slice(4) : organism;
  return trimmed
    .split('-')
    .filter((s) => s.length > 0)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}

function threadRuleConfig(
  rule: DomainRuleOverlayEntry,
  trait: FactoryTraitSignature,
  params: FactoryCallSiteParams,
  warnings: TranslationWarning[],
): void {
  if (!rule.config) return;
  const advertised = new Set(trait.overridableConfigKeys);
  const existing = params.traitOverrides?.[trait.name] ?? {};
  const existingConfig = existing.config ?? {};
  const merged: Record<string, FactoryParamValue> = { ...existingConfig };
  for (const [k, v] of Object.entries(rule.config)) {
    if (!advertised.has(k)) {
      warnings.push({
        field: `ruleOverlay.rules.${rule.id}.config.${k}`,
        reason: `trait "${trait.name}" does not advertise config key "${k}"`,
      });
      continue;
    }
    merged[k] = v;
  }
  if (Object.keys(merged).length > 0) {
    params.traitOverrides = {
      ...params.traitOverrides,
      [trait.name]: { ...existing, config: merged },
    };
  }
}

function applyOwnership(
  entry: OwnershipOverlayEntry,
  params: FactoryCallSiteParams,
  signature: FactorySignature,
  catalog: ReadonlyArray<FactorySignature> | undefined,
  warnings: TranslationWarning[],
): void {
  // Look first on the bound signature; then in the catalog (an
  // ExtraTrait emitted by a rule above may carry the ownerField knob).
  const local = signature.traits.find((t) =>
    t.overridableConfigKeys.includes('ownerField'),
  );
  if (local) {
    writeOwnerField(local.name, entry.ownerField, params);
    return;
  }
  if (catalog) {
    for (const sig of catalog) {
      const trait = sig.traits.find((t) =>
        t.overridableConfigKeys.includes('ownerField'),
      );
      if (trait) {
        writeOwnerField(trait.name, entry.ownerField, params);
        return;
      }
    }
  }
  warnings.push({
    field: `ruleOverlay.ownership.${entry.entity}`,
    reason: 'no trait in the bound signature or catalog advertises an `ownerField` config knob',
  });
}

function writeOwnerField(
  traitName: string,
  ownerField: string,
  params: FactoryCallSiteParams,
): void {
  const existing = params.traitOverrides?.[traitName] ?? {};
  const existingConfig = existing.config ?? {};
  params.traitOverrides = {
    ...params.traitOverrides,
    [traitName]: {
      ...existing,
      config: { ...existingConfig, ownerField },
    },
  };
}

// ---------------------------------------------------------------------------
// Leaf coercion — DomainField → EntityField. No `unknown`; the source
// type registry maps DomainFieldType → FieldType deterministically.
// ---------------------------------------------------------------------------

function lowerField(f: DomainField): EntityField | undefined {
  const schemaType = DOMAIN_TO_SCHEMA_FIELD_TYPE[f.fieldType];
  if (!schemaType) return undefined;
  const out: EntityField = {
    name: f.name,
    type: schemaType,
  };
  if (f.required === true) out.required = true;
  if (f.enumValues && f.enumValues.length > 0) out.values = [...f.enumValues];
  if (f.default !== undefined) out.default = lowerDefault(f.default);
  if (f.items) {
    const itemSchema = DOMAIN_TO_SCHEMA_FIELD_TYPE[f.items.type];
    if (itemSchema) out.items = { type: itemSchema };
  }
  return out;
}

function lowerDefault(d: DomainFieldDefault): EntityField['default'] {
  if (d === undefined || d === null) return d;
  if (typeof d === 'string' || typeof d === 'number' || typeof d === 'boolean') {
    return d;
  }
  if (Array.isArray(d)) {
    return d.map(lowerDefault) as EntityField['default'];
  }
  if (typeof d === 'object') {
    const out: Record<string, EntityField['default']> = {};
    for (const [k, v] of Object.entries(d)) out[k] = lowerDefault(v);
    return out as EntityField['default'];
  }
  return undefined;
}

function navItemToParamValue(item: PresentationNavItem): FactoryParamValue {
  const out: Record<string, FactoryParamValue> = {
    label: item.label,
    path: item.path,
  };
  if (item.icon) out.icon = item.icon;
  return out;
}

