/**
 * Deterministic translator: one `DomainDocument` slice + one chosen
 * `FactorySignature` → one `FactoryCallSite`. The agent picks the
 * signature upstream via embedding-search over the catalog; this
 * function does ZERO matching. It just lowers domain fields onto the
 * factory's advertised param surface, field-by-field.
 *
 * The binding (which `DomainEntity` / `DomainPage[]` map to this
 * orbital) is the agent's explicit decision and is passed in. No name
 * matching, no scoring, no tie-breaks.
 *
 * Adding a new domain concept means:
 *   1. Add a field on `DomainEntity` / `DomainPage` / `DomainBehavior`
 *      (`packages/almadar-core/src/domain-language/types.ts`).
 *   2. Make sure at least one factory signature advertises a
 *      consuming knob (Phase 1.5 gate — generated by
 *      almadar-pattern-sync from `.orb`).
 *   3. Add one helper-fn row below that lowers the new field into
 *      `FactoryCallSiteParams`.
 *
 * If a binding field has no signature consumer, the translator emits
 * a typed warning and SKIPS the field — that's the loud signal the
 * field shouldn't have been admitted to the language.
 */

import type { EntityField } from '../../types/field.js';
import type {
  DomainEntity,
  DomainField,
  DomainFieldDefault,
  DomainPage,
  FactoryCallSite,
  FactoryCallSiteParams,
  FactoryParamValue,
  FactorySignature,
  PresentationNavItem,
  PresentationOverlay,
} from '../types.js';
import { DOMAIN_TO_SCHEMA_FIELD_TYPE } from '../types.js';

/**
 * The slice of `DomainDocument` that maps onto the chosen signature.
 * The agent assembles this when it picks the signature: it knows
 * which `DomainEntity` / `DomainPage[]` are this orbital's
 * responsibility.
 */
export interface TranslationBinding {
  /** The single domain entity this signature's orbital owns. */
  entity: DomainEntity;
  /** Pages from the domain doc that map to this orbital's pages. The
   *  translator pairs them with `signature.pages[]` by name. */
  pages?: ReadonlyArray<DomainPage>;
}

export interface TranslationWarning {
  /** Dotted path of the domain field that couldn't be lowered. */
  field: string;
  /** Human-readable reason. */
  reason: string;
}

export interface TranslationResult {
  callSite: FactoryCallSite;
  warnings: ReadonlyArray<TranslationWarning>;
}

export function translateDomainToParams(
  binding: TranslationBinding,
  signature: FactorySignature,
  presentation?: PresentationOverlay,
): TranslationResult {
  const warnings: TranslationWarning[] = [];
  const params: FactoryCallSiteParams = {};

  applyEntityName(binding.entity, signature, params);
  applyEntityFields(binding.entity, signature, params, warnings);
  applyPersistence(binding.entity, signature, params, warnings);
  applyPagePaths(binding.pages ?? [], signature, params, warnings);
  applyPresentation(presentation, signature, params, warnings);

  return {
    callSite: {
      organism: signature.organism,
      orbital: signature.orbital,
      factoryPath: signature.factoryPath,
      params,
    },
    warnings,
  };
}

// ---------------------------------------------------------------------------
// Per-field lowering — one helper per row in the domain↔factory table.
// ---------------------------------------------------------------------------

function applyEntityName(
  entity: DomainEntity,
  signature: FactorySignature,
  params: FactoryCallSiteParams,
): void {
  if (signature.entities.length === 0) return;
  if (entity.name === signature.entities[0].name) return;
  params.entityName = entity.name;
}

function applyEntityFields(
  entity: DomainEntity,
  signature: FactorySignature,
  params: FactoryCallSiteParams,
  warnings: TranslationWarning[],
): void {
  if (signature.entities.length === 0) {
    if (entity.fields.length > 0) {
      warnings.push({
        field: `entity.${entity.name}.fields`,
        reason: 'factory signature does not advertise an entity surface',
      });
    }
    return;
  }
  const canonical = new Set(signature.entities[0].fields.map((f) => f.name));
  const extras: EntityField[] = [];
  for (const f of entity.fields) {
    if (canonical.has(f.name)) continue;
    const lowered = lowerField(f);
    if (lowered) extras.push(lowered);
  }
  if (extras.length > 0) params.entityFields = extras;
}

function applyPersistence(
  entity: DomainEntity,
  signature: FactorySignature,
  params: FactoryCallSiteParams,
  warnings: TranslationWarning[],
): void {
  if (!entity.persistence) return;
  if (signature.entities.length === 0) {
    warnings.push({
      field: `entity.${entity.name}.persistence`,
      reason: 'factory signature has no entity to apply persistence to',
    });
    return;
  }
  if (entity.persistence === signature.entities[0].persistence) return;
  params.persistence = entity.persistence;
}

function applyPagePaths(
  pages: ReadonlyArray<DomainPage>,
  signature: FactorySignature,
  params: FactoryCallSiteParams,
  warnings: TranslationWarning[],
): void {
  if (pages.length === 0) return;
  const sigPages = new Map(signature.pages.map((p) => [p.name, p]));
  const overrides: Record<string, string> = {};
  for (const p of pages) {
    const sig = sigPages.get(p.name);
    if (!sig) {
      warnings.push({
        field: `page.${p.name}.url`,
        reason: `factory signature has no page named "${p.name}"`,
      });
      continue;
    }
    if (sig.defaultPath !== p.url) overrides[p.name] = p.url;
  }
  if (Object.keys(overrides).length > 0) params.pagePaths = overrides;
}

function applyPresentation(
  overlay: PresentationOverlay | undefined,
  signature: FactorySignature,
  params: FactoryCallSiteParams,
  warnings: TranslationWarning[],
): void {
  if (!overlay?.navAdditions || overlay.navAdditions.length === 0) return;
  const target = signature.traits.find((t) =>
    t.overridableConfigKeys.includes('navItems'),
  );
  if (!target) {
    warnings.push({
      field: 'presentation.navAdditions',
      reason:
        'factory signature has no trait advertising a `navItems` config key',
    });
    return;
  }
  const existing = params.traitOverrides?.[target.name] ?? {};
  const existingConfig = existing.config ?? {};
  const items: ReadonlyArray<FactoryParamValue> = overlay.navAdditions.map(
    navItemToParamValue,
  );
  params.traitOverrides = {
    ...params.traitOverrides,
    [target.name]: {
      ...existing,
      config: { ...existingConfig, navItems: items },
    },
  };
}

// ---------------------------------------------------------------------------
// Leaf coercion — DomainField → EntityField. No `unknown`; the source
// type registry maps DomainFieldType → FieldType deterministically.
// ---------------------------------------------------------------------------

function lowerField(f: DomainField): EntityField | undefined {
  const schemaType = DOMAIN_TO_SCHEMA_FIELD_TYPE[f.fieldType];
  if (!schemaType) return undefined;
  const out: EntityField = {
    name: f.name,
    type: schemaType,
  };
  if (f.required === true) out.required = true;
  if (f.enumValues && f.enumValues.length > 0) out.values = [...f.enumValues];
  if (f.default !== undefined) out.default = lowerDefault(f.default);
  if (f.items) {
    const itemSchema = DOMAIN_TO_SCHEMA_FIELD_TYPE[f.items.type];
    if (itemSchema) out.items = { type: itemSchema };
  }
  return out;
}

function lowerDefault(d: DomainFieldDefault): EntityField['default'] {
  if (d === undefined || d === null) return d;
  if (typeof d === 'string' || typeof d === 'number' || typeof d === 'boolean') {
    return d;
  }
  if (Array.isArray(d)) {
    return d.map(lowerDefault) as EntityField['default'];
  }
  if (typeof d === 'object') {
    const out: Record<string, EntityField['default']> = {};
    for (const [k, v] of Object.entries(d)) out[k] = lowerDefault(v);
    return out as EntityField['default'];
  }
  return undefined;
}

function navItemToParamValue(item: PresentationNavItem): FactoryParamValue {
  const out: Record<string, FactoryParamValue> = {
    label: item.label,
    path: item.path,
  };
  if (item.icon) out.icon = item.icon;
  return out;
}

