/**
 * Validation error types — the shape emitted by every
 * `.orb` / `.lolo` validator pass.
 *
 * `ValidationError` is the wire shape: `{ code, path, message, suggestion? }`.
 * `code` is `ValidationErrorCode`, which is an OPEN `string` to let the
 * Rust validator emit new codes without an `@almadar/core` rev. The
 * `KNOWN_VALIDATION_ERROR_CODES` const documents the codes currently
 * emitted by the validator + lolo lower pipeline (extracted from
 * `orbital-rust/crates/orbital-compiler/src/phases/validation/` +
 * `orbital-rust/crates/orbital-lolo/src/`).
 *
 * Consumers that want to narrow a code to the closed known set use
 * `KnownValidationErrorCode`:
 *
 * ```ts
 * if (err.code in KNOWN_VALIDATION_ERROR_CODES) {
 *   // err.code is now narrowable to KnownValidationErrorCode for
 *   // exhaustive switch handling.
 * }
 * ```
 *
 * @packageDocumentation
 */

/**
 * One validation diagnostic emitted by the validator / lolo lower pipeline.
 *
 * - `code`: machine-readable identifier (see `KNOWN_VALIDATION_ERROR_CODES`).
 * - `path`: JSON pointer-like path into the failing schema location,
 *   e.g. `'orbitals[0].traits[2].stateMachine.transitions[1].effects[0]'`.
 * - `message`: human-readable description of the failure.
 * - `suggestion`: optional hint the validator may add to help the
 *   author / LLM fix the issue.
 */
export interface ValidationError {
  code: ValidationErrorCode;
  path: string;
  message: string;
  suggestion?: string;
}

/**
 * Validation error code — open `string` for forward-compat with the
 * Rust validator's evolving code set. Narrow to the closed known set
 * via `KnownValidationErrorCode` when exhaustive handling is needed.
 */
export type ValidationErrorCode = string;

/**
 * The result of a single validator pass: a boolean verdict plus the errors
 * and warnings (the validator wire shape, `ValidationError`).
 *
 * Distinct from `ValidationResults` (app.ts): that is the Firestore-persisted
 * app-document shape keyed on `ValidationIssue` (with `severity` + array path
 * + `validatedAt`). This `ValidationResult` is the in-process pass result keyed
 * on `ValidationError` (code + JSON-pointer string path + `suggestion`).
 * `ok === true` iff there are zero errors AND zero warnings.
 */
export interface ValidationResult {
  ok: boolean;
  errors: ValidationError[];
  warnings: ValidationError[];
}

/**
 * Closed set of validation codes the Rust validator + lolo lower
 * pipeline currently emit. Source-tagged: codes are extracted from
 * `orbital-rust/crates/orbital-compiler/src/phases/validation/**.rs`
 * and `orbital-rust/crates/orbital-lolo/src/**.rs`. Keep this in sync
 * with the Rust side; mismatches are caught by the Rust validator's
 * own unit tests, which assert the emitted code-set matches an
 * exported manifest.
 *
 * Categories (prefix → meaning):
 * - `ORB_BINDING_*` — binding (`@entity.X`, `@payload.Y`, ...) issues
 * - `ORB_E_*` / `ORB_EFF_*` / `ORB_EMIT_*` — entity / effect / emit
 * - `ORB_GEN_*` — generic / cross-cutting structure
 * - `ORB_O_*` / `ORB_P_*` / `ORB_S_*` / `ORB_SM_*` / `ORB_T_*` —
 *   orbital / page / schema / state-machine / trait
 * - `ORB_QUERY_*` — query / search behaviors
 * - `ORB_RUI_*` — render-UI binding + prop validation
 * - `ORB_SLOT_*` — UI-slot conflict / contention
 * - `ORB_SVC_*` / `ORB_UI_*` — service / UI primitives
 * - `ORB_X_*` — cross-orbital constraints (listens, emits, IDs)
 */
export const KNOWN_VALIDATION_ERROR_CODES = {
  // Binding (`@entity.X`, `@payload.Y`, `@state.Z`, `@now`, ...)
  ORB_BINDING_ENTITY_FIELD_NEVER_SET: 'ORB_BINDING_ENTITY_FIELD_NEVER_SET',
  ORB_BINDING_ENTITY_FIELD_NOT_FOUND: 'ORB_BINDING_ENTITY_FIELD_NOT_FOUND',
  ORB_BINDING_INVALID_FIELD_NAME: 'ORB_BINDING_INVALID_FIELD_NAME',
  ORB_BINDING_INVALID_FORMAT: 'ORB_BINDING_INVALID_FORMAT',
  ORB_BINDING_INVALID_PATH: 'ORB_BINDING_INVALID_PATH',
  ORB_BINDING_NOW_NO_PATH: 'ORB_BINDING_NOW_NO_PATH',
  ORB_BINDING_PAYLOAD_FIELD_UNDECLARED: 'ORB_BINDING_PAYLOAD_FIELD_UNDECLARED',
  ORB_BINDING_PAYLOAD_IN_TICK: 'ORB_BINDING_PAYLOAD_IN_TICK',
  ORB_BINDING_PAYLOAD_TYPE_INCOMPATIBLE: 'ORB_BINDING_PAYLOAD_TYPE_INCOMPATIBLE',
  ORB_BINDING_SET_TARGET_MISSING_PATH: 'ORB_BINDING_SET_TARGET_MISSING_PATH',
  ORB_BINDING_STATE_NO_PATH: 'ORB_BINDING_STATE_NO_PATH',
  ORB_BINDING_TRAIT_CYCLE: 'ORB_BINDING_TRAIT_CYCLE',
  ORB_BINDING_TRAIT_INVALID_FORMAT: 'ORB_BINDING_TRAIT_INVALID_FORMAT',
  ORB_BINDING_TRAIT_INVALID_POSITION: 'ORB_BINDING_TRAIT_INVALID_POSITION',
  ORB_BINDING_TRAIT_MISSING_NAME: 'ORB_BINDING_TRAIT_MISSING_NAME',
  ORB_BINDING_TRAIT_SELF_REFERENCE: 'ORB_BINDING_TRAIT_SELF_REFERENCE',
  ORB_BINDING_TRAIT_UNKNOWN: 'ORB_BINDING_TRAIT_UNKNOWN',
  ORB_BINDING_UNKNOWN_ENTITY: 'ORB_BINDING_UNKNOWN_ENTITY',
  ORB_BINDING_UNKNOWN_ROOT: 'ORB_BINDING_UNKNOWN_ROOT',

  // Entity / field
  ORB_E_DUPLICATE_FIELD: 'ORB_E_DUPLICATE_FIELD',
  ORB_E_EMPTY_ENUM_VALUES: 'ORB_E_EMPTY_ENUM_VALUES',
  ORB_E_INVALID_FIELD_NAME: 'ORB_E_INVALID_FIELD_NAME',
  ORB_E_INVALID_FIELD_TYPE: 'ORB_E_INVALID_FIELD_TYPE',
  ORB_E_INVALID_RELATION: 'ORB_E_INVALID_RELATION',
  ORB_E_LITERAL_UNION_DEFAULT_MISMATCH: 'ORB_E_LITERAL_UNION_DEFAULT_MISMATCH',
  ORB_E_MISSING_COLLECTION: 'ORB_E_MISSING_COLLECTION',
  ORB_E_MISSING_NAME: 'ORB_E_MISSING_NAME',
  ORB_E_NO_FIELDS: 'ORB_E_NO_FIELDS',

  // Effect / emit
  ORB_EFF_CALL_SERVICE_MISSING_ACTION: 'ORB_EFF_CALL_SERVICE_MISSING_ACTION',
  ORB_EFF_CALL_SERVICE_MISSING_HANDLERS: 'ORB_EFF_CALL_SERVICE_MISSING_HANDLERS',
  ORB_EFF_CALL_SERVICE_MISSING_SERVICE: 'ORB_EFF_CALL_SERVICE_MISSING_SERVICE',
  ORB_EFF_EMIT_INVALID_NAME: 'ORB_EFF_EMIT_INVALID_NAME',
  ORB_EFF_EMIT_KEY_INVALID: 'ORB_EFF_EMIT_KEY_INVALID',
  ORB_EFF_EMIT_UNDECLARED_EVENT: 'ORB_EFF_EMIT_UNDECLARED_EVENT',
  ORB_EFF_FETCH_INVALID_ENTITY: 'ORB_EFF_FETCH_INVALID_ENTITY',
  ORB_EFF_FETCH_INVALID_INCLUDE: 'ORB_EFF_FETCH_INVALID_INCLUDE',
  ORB_EFF_MISSING_FETCH_FOR_ENTITY: 'ORB_EFF_MISSING_FETCH_FOR_ENTITY',
  ORB_EFF_MISSING_REQUIRED_EMIT: 'ORB_EFF_MISSING_REQUIRED_EMIT',
  ORB_EFF_NAVIGATE_MISSING_PAYLOAD: 'ORB_EFF_NAVIGATE_MISSING_PAYLOAD',
  ORB_EFF_NAVIGATE_TARGET_UNREACHABLE: 'ORB_EFF_NAVIGATE_TARGET_UNREACHABLE',
  ORB_EFF_SET_INVALID_BINDING: 'ORB_EFF_SET_INVALID_BINDING',
  ORB_EFF_SET_PAYLOAD_NOT_ALLOWED: 'ORB_EFF_SET_PAYLOAD_NOT_ALLOWED',
  ORB_EFF_SLOT_CONFLICT: 'ORB_EFF_SLOT_CONFLICT',
  ORB_EFF_UNKNOWN_TYPE: 'ORB_EFF_UNKNOWN_TYPE',
  ORB_EMIT_DECLARED_BUT_UNFIRED: 'ORB_EMIT_DECLARED_BUT_UNFIRED',
  ORB_EMIT_PAYLOAD_EXTRA_FIELD: 'ORB_EMIT_PAYLOAD_EXTRA_FIELD',
  ORB_EMIT_PAYLOAD_FIELD_TYPE_MISMATCH: 'ORB_EMIT_PAYLOAD_FIELD_TYPE_MISMATCH',
  ORB_EMIT_PAYLOAD_MISSING_REQUIRED: 'ORB_EMIT_PAYLOAD_MISSING_REQUIRED',
  ORB_EMIT_SUCCESS_PAYLOAD_RETURN_MISMATCH: 'ORB_EMIT_SUCCESS_PAYLOAD_RETURN_MISMATCH',

  // Generic / cross-cutting structure
  ORB_GEN_DUPLICATE: 'ORB_GEN_DUPLICATE',
  ORB_GEN_INVALID_REFERENCE: 'ORB_GEN_INVALID_REFERENCE',
  ORB_GEN_INVALID_VALUE: 'ORB_GEN_INVALID_VALUE',
  ORB_GEN_MISSING_FIELD: 'ORB_GEN_MISSING_FIELD',

  // Orbital
  ORB_O_MISSING_PAGES: 'ORB_O_MISSING_PAGES',

  // Page
  ORB_P_DUPLICATE_PATH: 'ORB_P_DUPLICATE_PATH',
  ORB_P_EMPTY_TRAITS: 'ORB_P_EMPTY_TRAITS',
  ORB_P_INVALID_PATH: 'ORB_P_INVALID_PATH',
  ORB_P_INVALID_TRAIT_REF: 'ORB_P_INVALID_TRAIT_REF',
  ORB_P_INVALID_VIEW_TYPE: 'ORB_P_INVALID_VIEW_TYPE',
  ORB_P_MISSING_NAME: 'ORB_P_MISSING_NAME',
  ORB_P_MISSING_PATH: 'ORB_P_MISSING_PATH',
  ORB_P_MISSING_TRAITS: 'ORB_P_MISSING_TRAITS',
  ORB_P_SECTIONS_FORBIDDEN: 'ORB_P_SECTIONS_FORBIDDEN',

  // Query / search behaviors
  ORB_QUERY_MISSING_RECOMMENDED: 'ORB_QUERY_MISSING_RECOMMENDED',
  ORB_QUERY_MISSING_SEARCH: 'ORB_QUERY_MISSING_SEARCH',
  ORB_QUERY_UNKNOWN_SINGLETON: 'ORB_QUERY_UNKNOWN_SINGLETON',
  ORB_QUERY_UNSUPPORTED_PATTERN: 'ORB_QUERY_UNSUPPORTED_PATTERN',
  ORB_QUERY_UNUSED_SINGLETON: 'ORB_QUERY_UNUSED_SINGLETON',

  // Render-UI binding + prop validation
  ORB_RUI_BINDING_TYPE_MISMATCH: 'ORB_RUI_BINDING_TYPE_MISMATCH',
  ORB_RUI_ELEMENT_SHAPE_MISMATCH: 'ORB_RUI_ELEMENT_SHAPE_MISMATCH',
  ORB_RUI_EVENT_BINDING_PAYLOAD_MISMATCH: 'ORB_RUI_EVENT_BINDING_PAYLOAD_MISMATCH',
  ORB_RUI_INVALID_FIELD_PATH: 'ORB_RUI_INVALID_FIELD_PATH',
  ORB_RUI_INVALID_ITEM_ACTION: 'ORB_RUI_INVALID_ITEM_ACTION',
  ORB_RUI_INVALID_PATTERN: 'ORB_RUI_INVALID_PATTERN',
  ORB_RUI_INVALID_PROP: 'ORB_RUI_INVALID_PROP',
  ORB_RUI_INVALID_SLOT: 'ORB_RUI_INVALID_SLOT',
  ORB_RUI_MISSING_ACTION: 'ORB_RUI_MISSING_ACTION',
  ORB_RUI_MISSING_PATTERN_TYPE: 'ORB_RUI_MISSING_PATTERN_TYPE',
  ORB_RUI_MISSING_REQUIRED_PROP: 'ORB_RUI_MISSING_REQUIRED_PROP',
  ORB_RUI_PROP_TYPE_MISMATCH: 'ORB_RUI_PROP_TYPE_MISMATCH',
  ORB_RUI_UNKNOWN_ITEM_ACTION_PROP: 'ORB_RUI_UNKNOWN_ITEM_ACTION_PROP',

  // Schema-level
  ORB_S_EMPTY_VERSION: 'ORB_S_EMPTY_VERSION',
  ORB_S_MISSING_NAME: 'ORB_S_MISSING_NAME',
  ORB_S_NO_ORBITALS: 'ORB_S_NO_ORBITALS',

  // UI slots
  ORB_SLOT_CONTENTION: 'ORB_SLOT_CONTENTION',
  ORB_SLOT_CONTENTION_RUNTIME: 'ORB_SLOT_CONTENTION_RUNTIME',
  ORB_SLOT_HUD_NON_GAME: 'ORB_SLOT_HUD_NON_GAME',
  ORB_SLOT_INVALID_NAME: 'ORB_SLOT_INVALID_NAME',
  ORB_SLOT_INVALID_NESTING: 'ORB_SLOT_INVALID_NESTING',
  ORB_SLOT_MAIN_NOT_COVERED: 'ORB_SLOT_MAIN_NOT_COVERED',
  ORB_SLOT_PRIORITY_CONFLICT: 'ORB_SLOT_PRIORITY_CONFLICT',

  // Service
  ORB_SVC_DUPLICATE_NAME: 'ORB_SVC_DUPLICATE_NAME',
  ORB_SVC_INVALID_INTEGRATOR: 'ORB_SVC_INVALID_INTEGRATOR',
  ORB_SVC_INVALID_URL: 'ORB_SVC_INVALID_URL',
  ORB_SVC_MISSING_BASE_URL: 'ORB_SVC_MISSING_BASE_URL',
  ORB_SVC_MISSING_CAPABILITIES: 'ORB_SVC_MISSING_CAPABILITIES',
  ORB_SVC_MISSING_EVENTS: 'ORB_SVC_MISSING_EVENTS',
  ORB_SVC_MISSING_SERVER_PATH: 'ORB_SVC_MISSING_SERVER_PATH',
  ORB_SVC_RESERVED_EVENT: 'ORB_SVC_RESERVED_EVENT',
  ORB_SVC_UNKNOWN_TYPE: 'ORB_SVC_UNKNOWN_TYPE',

  // Trait
  ORB_T_CONFIG_OBJECT_ARRAY_FORBIDDEN: 'ORB_T_CONFIG_OBJECT_ARRAY_FORBIDDEN',
  ORB_T_CONFIG_SHAPE_MISMATCH: 'ORB_T_CONFIG_SHAPE_MISMATCH',
  ORB_T_CONFIG_TIER_INVALID: 'ORB_T_CONFIG_TIER_INVALID',
  ORB_T_DEPRECATED_UI: 'ORB_T_DEPRECATED_UI',
  ORB_T_DUPLICATE_NAME: 'ORB_T_DUPLICATE_NAME',
  ORB_T_DUPLICATE_STATE: 'ORB_T_DUPLICATE_STATE',
  ORB_T_DUPLICATE_TRANSITION: 'ORB_T_DUPLICATE_TRANSITION',
  ORB_T_ENTITY_NAME_SHADOWS_TRAIT_UNION: 'ORB_T_ENTITY_NAME_SHADOWS_TRAIT_UNION',
  ORB_T_EVENT_TYPE_WRONG_KIND: 'ORB_T_EVENT_TYPE_WRONG_KIND',
  ORB_T_EVT_DUPLICATE: 'ORB_T_EVT_DUPLICATE',
  ORB_T_EVT_EXTERNAL_MISSING_PAYLOAD: 'ORB_T_EVT_EXTERNAL_MISSING_PAYLOAD',
  ORB_T_EVT_INVALID_NAME: 'ORB_T_EVT_INVALID_NAME',
  ORB_T_EVT_SCOPE_MISMATCH: 'ORB_T_EVT_SCOPE_MISMATCH',
  ORB_T_EVT_TICK_UNDECLARED: 'ORB_T_EVT_TICK_UNDECLARED',
  ORB_T_EVT_UNDECLARED: 'ORB_T_EVT_UNDECLARED',
  ORB_T_INIT_MISSING_FETCH: 'ORB_T_INIT_MISSING_FETCH',
  ORB_T_INVALID_CATEGORY: 'ORB_T_INVALID_CATEGORY',
  ORB_T_INVALID_FORMAT: 'ORB_T_INVALID_FORMAT',
  ORB_T_INVALID_PATTERN_DEFAULT: 'ORB_T_INVALID_PATTERN_DEFAULT',
  ORB_T_INVALID_SLOT_DEFAULT: 'ORB_T_INVALID_SLOT_DEFAULT',
  ORB_T_INVALID_TRANSITION: 'ORB_T_INVALID_TRANSITION',
  ORB_T_MISSING_INIT_TRANSITION: 'ORB_T_MISSING_INIT_TRANSITION',
  ORB_T_MISSING_RENDER_UI: 'ORB_T_MISSING_RENDER_UI',
  ORB_T_MULTIPLE_INITIAL_STATES: 'ORB_T_MULTIPLE_INITIAL_STATES',
  ORB_T_NO_INITIAL_STATE: 'ORB_T_NO_INITIAL_STATE',
  ORB_T_TYPE_ANNOTATION_MISMATCH: 'ORB_T_TYPE_ANNOTATION_MISMATCH',
  ORB_T_TYPE_COMPOSITION_CONFLICT: 'ORB_T_TYPE_COMPOSITION_CONFLICT',
  ORB_T_TYPE_CYCLE: 'ORB_T_TYPE_CYCLE',
  ORB_T_TYPE_KIND_MISMATCH: 'ORB_T_TYPE_KIND_MISMATCH',
  ORB_T_TYPE_UNKNOWN: 'ORB_T_TYPE_UNKNOWN',
  ORB_T_TYPE_UNKNOWN_PARAM: 'ORB_T_TYPE_UNKNOWN_PARAM',
  ORB_T_TYPE_WRONG_ARG_COUNT: 'ORB_T_TYPE_WRONG_ARG_COUNT',
  ORB_T_UNDEFINED_EVENT: 'ORB_T_UNDEFINED_EVENT',
  ORB_T_UNDEFINED_TRAIT: 'ORB_T_UNDEFINED_TRAIT',

  // UI primitives (icons, etc.)
  ORB_UI_ICON_EMPTY: 'ORB_UI_ICON_EMPTY',
  ORB_UI_ICON_INVALID_FORMAT: 'ORB_UI_ICON_INVALID_FORMAT',
  ORB_UI_ICON_NOT_FOUND: 'ORB_UI_ICON_NOT_FOUND',

  // Cross-orbital constraints (listens, emits, IDs, payloads)
  ORB_X_CIRCULAR_DEPENDENCY: 'ORB_X_CIRCULAR_DEPENDENCY',
  ORB_X_CROSS_EMITTER_DECLARED_PAYLOAD_MISMATCH: 'ORB_X_CROSS_EMITTER_DECLARED_PAYLOAD_MISMATCH',
  ORB_X_DUPLICATE_ENTITY: 'ORB_X_DUPLICATE_ENTITY',
  ORB_X_EVENT_COLLISION: 'ORB_X_EVENT_COLLISION',
  ORB_X_INTERNAL_EVENT_EXPOSED: 'ORB_X_INTERNAL_EVENT_EXPOSED',
  ORB_X_LISTEN_SOURCE_UNRESOLVED: 'ORB_X_LISTEN_SOURCE_UNRESOLVED',
  ORB_X_MISSING_ORBITAL_NAME: 'ORB_X_MISSING_ORBITAL_NAME',
  ORB_X_ORPHAN_LISTENER: 'ORB_X_ORPHAN_LISTENER',
  ORB_X_PAYLOAD_MISMATCH: 'ORB_X_PAYLOAD_MISMATCH',
  ORB_X_RENDER_UI_EVENT_LITERAL_STALE: 'ORB_X_RENDER_UI_EVENT_LITERAL_STALE',
  ORB_X_UNRESOLVED_PATTERN_FIELD_REF: 'ORB_X_UNRESOLVED_PATTERN_FIELD_REF',
  ORB_X_UNUSED_EMISSION: 'ORB_X_UNUSED_EMISSION',
} as const;

/**
 * Narrow union of the codes documented in `KNOWN_VALIDATION_ERROR_CODES`.
 * Use this in exhaustive `switch` handlers; use the broader
 * `ValidationErrorCode` (open `string`) anywhere a fresh validator-side
 * code could plausibly arrive.
 */
export type KnownValidationErrorCode =
  typeof KNOWN_VALIDATION_ERROR_CODES[keyof typeof KNOWN_VALIDATION_ERROR_CODES];

/**
 * Type guard: is the given code a known one? After the guard returns
 * true, the code can be narrowed to `KnownValidationErrorCode` via a
 * separate cast, because the type system can't track `in` against
 * `as const` records without an explicit narrowing helper.
 */
export function isKnownValidationErrorCode(
  code: ValidationErrorCode,
): boolean {
  return code in KNOWN_VALIDATION_ERROR_CODES;
}
