/**
 * THEME_PRESETS — the built-in `ThemeDefinition` presets. GENERATED by
 * `scripts/generate-theme-index.ts` from `themes/*.json` (the directory is
 * the registry): add a JSON file and rebuild, never edit this file.
 *
 * These JSON files are the SOURCE: `almadar-pattern-sync`'s `themes` step
 * regenerates `@almadar/ui`'s CSS presets from them through
 * `themeTokensToCssVars`, and `orbital-core`'s `build.rs` bakes the same
 * directory into the kernel. Each import is validated + typed by
 * `ThemeDefinitionSchema` at load time — a malformed preset fails the moment
 * this module is imported, not silently.
 */

import almadarTheme from '../../themes/almadar.json' with { type: 'json' };
import almadarHeritageTheme from '../../themes/almadar-heritage.json' with { type: 'json' };
import almadarWebsiteTheme from '../../themes/almadar-website.json' with { type: 'json' };
import aquaTheme from '../../themes/aqua.json' with { type: 'json' };
import arabesqueTheme from '../../themes/arabesque.json' with { type: 'json' };
import artDecoTheme from '../../themes/art-deco.json' with { type: 'json' };
import artNouveauTheme from '../../themes/art-nouveau.json' with { type: 'json' };
import atelierTheme from '../../themes/atelier.json' with { type: 'json' };
import bauhausTheme from '../../themes/bauhaus.json' with { type: 'json' };
import bloombergDenseTheme from '../../themes/bloomberg-dense.json' with { type: 'json' };
import blueprintTheme from '../../themes/blueprint.json' with { type: 'json' };
import clayTheme from '../../themes/clay.json' with { type: 'json' };
import comicTheme from '../../themes/comic.json' with { type: 'json' };
import constructivistTheme from '../../themes/constructivist.json' with { type: 'json' };
import corporateTheme from '../../themes/corporate.json' with { type: 'json' };
import cyberpunkTheme from '../../themes/cyberpunk.json' with { type: 'json' };
import frutigerAeroTheme from '../../themes/frutiger-aero.json' with { type: 'json' };
import gameAdventureTheme from '../../themes/game-adventure.json' with { type: 'json' };
import gameRpgTheme from '../../themes/game-rpg.json' with { type: 'json' };
import gameSciFiTheme from '../../themes/game-sci-fi.json' with { type: 'json' };
import gameUiPackTheme from '../../themes/game-ui-pack.json' with { type: 'json' };
import gazetteTheme from '../../themes/gazette.json' with { type: 'json' };
import glassTheme from '../../themes/glass.json' with { type: 'json' };
import gothicTheme from '../../themes/gothic.json' with { type: 'json' };
import inkWashTheme from '../../themes/ink-wash.json' with { type: 'json' };
import kawaiiTheme from '../../themes/kawaii.json' with { type: 'json' };
import kflowTheme from '../../themes/kflow.json' with { type: 'json' };
import kioskTheme from '../../themes/kiosk.json' with { type: 'json' };
import linearCleanTheme from '../../themes/linear-clean.json' with { type: 'json' };
import luxuryTheme from '../../themes/luxury.json' with { type: 'json' };
import macClassicTheme from '../../themes/mac-classic.json' with { type: 'json' };
import materialTheme from '../../themes/material.json' with { type: 'json' };
import memphisTheme from '../../themes/memphis.json' with { type: 'json' };
import midCenturyTheme from '../../themes/mid-century.json' with { type: 'json' };
import minimalistTheme from '../../themes/minimalist.json' with { type: 'json' };
import mudclothTheme from '../../themes/mudcloth.json' with { type: 'json' };
import nataTheme from '../../themes/nata.json' with { type: 'json' };
import neonTheme from '../../themes/neon.json' with { type: 'json' };
import neumorphicTheme from '../../themes/neumorphic.json' with { type: 'json' };
import newsprintTheme from '../../themes/newsprint.json' with { type: 'json' };
import notionEditorialTheme from '../../themes/notion-editorial.json' with { type: 'json' };
import orbTheme from '../../themes/orb.json' with { type: 'json' };
import pixelTheme from '../../themes/pixel.json' with { type: 'json' };
import prismTheme from '../../themes/prism.json' with { type: 'json' };
import rawiTheme from '../../themes/rawi.json' with { type: 'json' };
import retroTheme from '../../themes/retro.json' with { type: 'json' };
import risographTheme from '../../themes/risograph.json' with { type: 'json' };
import scandiTheme from '../../themes/scandi.json' with { type: 'json' };
import sketchTheme from '../../themes/sketch.json' with { type: 'json' };
import solarpunkTheme from '../../themes/solarpunk.json' with { type: 'json' };
import steampunkTheme from '../../themes/steampunk.json' with { type: 'json' };
import swissTheme from '../../themes/swiss.json' with { type: 'json' };
import terminalTheme from '../../themes/terminal.json' with { type: 'json' };
import traitWarsTheme from '../../themes/trait-wars.json' with { type: 'json' };
import ukiyoETheme from '../../themes/ukiyo-e.json' with { type: 'json' };
import vaporwaveTheme from '../../themes/vaporwave.json' with { type: 'json' };
import victorianTheme from '../../themes/victorian.json' with { type: 'json' };
import wabiSabiTheme from '../../themes/wabi-sabi.json' with { type: 'json' };
import win95Theme from '../../themes/win95.json' with { type: 'json' };
import wireframeTheme from '../../themes/wireframe.json' with { type: 'json' };
import zineTheme from '../../themes/zine.json' with { type: 'json' };

import { ThemeDefinitionSchema } from '../types/domain.js';
import type { ThemeDefinition } from '../types/domain.js';

export const THEME_PRESETS: Record<string, ThemeDefinition> = {
  almadar: ThemeDefinitionSchema.parse(almadarTheme),
  'almadar-heritage': ThemeDefinitionSchema.parse(almadarHeritageTheme),
  'almadar-website': ThemeDefinitionSchema.parse(almadarWebsiteTheme),
  aqua: ThemeDefinitionSchema.parse(aquaTheme),
  arabesque: ThemeDefinitionSchema.parse(arabesqueTheme),
  'art-deco': ThemeDefinitionSchema.parse(artDecoTheme),
  'art-nouveau': ThemeDefinitionSchema.parse(artNouveauTheme),
  atelier: ThemeDefinitionSchema.parse(atelierTheme),
  bauhaus: ThemeDefinitionSchema.parse(bauhausTheme),
  'bloomberg-dense': ThemeDefinitionSchema.parse(bloombergDenseTheme),
  blueprint: ThemeDefinitionSchema.parse(blueprintTheme),
  clay: ThemeDefinitionSchema.parse(clayTheme),
  comic: ThemeDefinitionSchema.parse(comicTheme),
  constructivist: ThemeDefinitionSchema.parse(constructivistTheme),
  corporate: ThemeDefinitionSchema.parse(corporateTheme),
  cyberpunk: ThemeDefinitionSchema.parse(cyberpunkTheme),
  'frutiger-aero': ThemeDefinitionSchema.parse(frutigerAeroTheme),
  'game-adventure': ThemeDefinitionSchema.parse(gameAdventureTheme),
  'game-rpg': ThemeDefinitionSchema.parse(gameRpgTheme),
  'game-sci-fi': ThemeDefinitionSchema.parse(gameSciFiTheme),
  'game-ui-pack': ThemeDefinitionSchema.parse(gameUiPackTheme),
  gazette: ThemeDefinitionSchema.parse(gazetteTheme),
  glass: ThemeDefinitionSchema.parse(glassTheme),
  gothic: ThemeDefinitionSchema.parse(gothicTheme),
  'ink-wash': ThemeDefinitionSchema.parse(inkWashTheme),
  kawaii: ThemeDefinitionSchema.parse(kawaiiTheme),
  kflow: ThemeDefinitionSchema.parse(kflowTheme),
  kiosk: ThemeDefinitionSchema.parse(kioskTheme),
  'linear-clean': ThemeDefinitionSchema.parse(linearCleanTheme),
  luxury: ThemeDefinitionSchema.parse(luxuryTheme),
  'mac-classic': ThemeDefinitionSchema.parse(macClassicTheme),
  material: ThemeDefinitionSchema.parse(materialTheme),
  memphis: ThemeDefinitionSchema.parse(memphisTheme),
  'mid-century': ThemeDefinitionSchema.parse(midCenturyTheme),
  minimalist: ThemeDefinitionSchema.parse(minimalistTheme),
  mudcloth: ThemeDefinitionSchema.parse(mudclothTheme),
  nata: ThemeDefinitionSchema.parse(nataTheme),
  neon: ThemeDefinitionSchema.parse(neonTheme),
  neumorphic: ThemeDefinitionSchema.parse(neumorphicTheme),
  newsprint: ThemeDefinitionSchema.parse(newsprintTheme),
  'notion-editorial': ThemeDefinitionSchema.parse(notionEditorialTheme),
  orb: ThemeDefinitionSchema.parse(orbTheme),
  pixel: ThemeDefinitionSchema.parse(pixelTheme),
  prism: ThemeDefinitionSchema.parse(prismTheme),
  rawi: ThemeDefinitionSchema.parse(rawiTheme),
  retro: ThemeDefinitionSchema.parse(retroTheme),
  risograph: ThemeDefinitionSchema.parse(risographTheme),
  scandi: ThemeDefinitionSchema.parse(scandiTheme),
  sketch: ThemeDefinitionSchema.parse(sketchTheme),
  solarpunk: ThemeDefinitionSchema.parse(solarpunkTheme),
  steampunk: ThemeDefinitionSchema.parse(steampunkTheme),
  swiss: ThemeDefinitionSchema.parse(swissTheme),
  terminal: ThemeDefinitionSchema.parse(terminalTheme),
  'trait-wars': ThemeDefinitionSchema.parse(traitWarsTheme),
  'ukiyo-e': ThemeDefinitionSchema.parse(ukiyoETheme),
  vaporwave: ThemeDefinitionSchema.parse(vaporwaveTheme),
  victorian: ThemeDefinitionSchema.parse(victorianTheme),
  'wabi-sabi': ThemeDefinitionSchema.parse(wabiSabiTheme),
  win95: ThemeDefinitionSchema.parse(win95Theme),
  wireframe: ThemeDefinitionSchema.parse(wireframeTheme),
  zine: ThemeDefinitionSchema.parse(zineTheme),
};

export { MIN_TEXT_CONTRAST, contrastRatio, themeOverrideIssues, type ThemeOverrideIssue } from './contrast.js';
