/**
 * THEME_PRESETS — the built-in `ThemeDefinition` presets. GENERATED by
 * `scripts/generate-theme-index.ts` from `themes/*.json` (the directory is
 * the registry): add a JSON file and rebuild, never edit this file.
 *
 * These JSON files are the SOURCE: `almadar-pattern-sync`'s `themes` step
 * regenerates `@almadar/ui`'s CSS presets from them through
 * `themeTokensToCssVars`, and `orbital-core`'s `build.rs` bakes the same
 * directory into the kernel. Each import is validated + typed by
 * `ThemeDefinitionSchema` at load time — a malformed preset fails the moment
 * this module is imported, not silently.
 */

import almadarTheme from '../../themes/almadar.json' with { type: 'json' };
import almadarWebsiteTheme from '../../themes/almadar-website.json' with { type: 'json' };
import atelierTheme from '../../themes/atelier.json' with { type: 'json' };
import bloombergDenseTheme from '../../themes/bloomberg-dense.json' with { type: 'json' };
import clayTheme from '../../themes/clay.json' with { type: 'json' };
import comicTheme from '../../themes/comic.json' with { type: 'json' };
import corporateTheme from '../../themes/corporate.json' with { type: 'json' };
import gameAdventureTheme from '../../themes/game-adventure.json' with { type: 'json' };
import gameRpgTheme from '../../themes/game-rpg.json' with { type: 'json' };
import gameSciFiTheme from '../../themes/game-sci-fi.json' with { type: 'json' };
import gameUiPackTheme from '../../themes/game-ui-pack.json' with { type: 'json' };
import gazetteTheme from '../../themes/gazette.json' with { type: 'json' };
import glassTheme from '../../themes/glass.json' with { type: 'json' };
import kioskTheme from '../../themes/kiosk.json' with { type: 'json' };
import linearCleanTheme from '../../themes/linear-clean.json' with { type: 'json' };
import minimalistTheme from '../../themes/minimalist.json' with { type: 'json' };
import neonTheme from '../../themes/neon.json' with { type: 'json' };
import notionEditorialTheme from '../../themes/notion-editorial.json' with { type: 'json' };
import prismTheme from '../../themes/prism.json' with { type: 'json' };
import retroTheme from '../../themes/retro.json' with { type: 'json' };
import terminalTheme from '../../themes/terminal.json' with { type: 'json' };
import traitWarsTheme from '../../themes/trait-wars.json' with { type: 'json' };
import wireframeTheme from '../../themes/wireframe.json' with { type: 'json' };

import { ThemeDefinitionSchema } from '../types/domain.js';
import type { ThemeDefinition } from '../types/domain.js';

export const THEME_PRESETS: Record<string, ThemeDefinition> = {
  almadar: ThemeDefinitionSchema.parse(almadarTheme),
  'almadar-website': ThemeDefinitionSchema.parse(almadarWebsiteTheme),
  atelier: ThemeDefinitionSchema.parse(atelierTheme),
  'bloomberg-dense': ThemeDefinitionSchema.parse(bloombergDenseTheme),
  clay: ThemeDefinitionSchema.parse(clayTheme),
  comic: ThemeDefinitionSchema.parse(comicTheme),
  corporate: ThemeDefinitionSchema.parse(corporateTheme),
  'game-adventure': ThemeDefinitionSchema.parse(gameAdventureTheme),
  'game-rpg': ThemeDefinitionSchema.parse(gameRpgTheme),
  'game-sci-fi': ThemeDefinitionSchema.parse(gameSciFiTheme),
  'game-ui-pack': ThemeDefinitionSchema.parse(gameUiPackTheme),
  gazette: ThemeDefinitionSchema.parse(gazetteTheme),
  glass: ThemeDefinitionSchema.parse(glassTheme),
  kiosk: ThemeDefinitionSchema.parse(kioskTheme),
  'linear-clean': ThemeDefinitionSchema.parse(linearCleanTheme),
  minimalist: ThemeDefinitionSchema.parse(minimalistTheme),
  neon: ThemeDefinitionSchema.parse(neonTheme),
  'notion-editorial': ThemeDefinitionSchema.parse(notionEditorialTheme),
  prism: ThemeDefinitionSchema.parse(prismTheme),
  retro: ThemeDefinitionSchema.parse(retroTheme),
  terminal: ThemeDefinitionSchema.parse(terminalTheme),
  'trait-wars': ThemeDefinitionSchema.parse(traitWarsTheme),
  wireframe: ThemeDefinitionSchema.parse(wireframeTheme),
};
