/**
 * Generates `src/themes/index.ts` (`THEME_PRESETS`) from the files under
 * `themes/*.json` — the directory is the registry, never a hand list (ledger
 * §168). Run: `pnpm --filter @almadar/core run build:themes` (wired into
 * `build`, before the fixture step and `tsup`).
 */
import { readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const PACKAGE_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const THEMES_DIR = join(PACKAGE_ROOT, 'themes');
const OUT = join(PACKAGE_ROOT, 'src', 'themes', 'index.ts');

const names = readdirSync(THEMES_DIR)
  .filter((f) => f.endsWith('.json'))
  .map((f) => f.slice(0, -'.json'.length))
  .sort();

const identifier = (name: string): string =>
  `${name.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase())}Theme`;
const key = (name: string): string => (/^[a-z][a-zA-Z0-9]*$/.test(name) ? name : `'${name}'`);

const lines: string[] = [
  '/**',
  ' * THEME_PRESETS — the built-in `ThemeDefinition` presets. GENERATED by',
  ' * `scripts/generate-theme-index.ts` from `themes/*.json` (the directory is',
  ' * the registry): add a JSON file and rebuild, never edit this file.',
  ' *',
  ' * These JSON files are the SOURCE: `almadar-pattern-sync`\'s `themes` step',
  ' * regenerates `@almadar/ui`\'s CSS presets from them through',
  ' * `themeTokensToCssVars`, and `orbital-core`\'s `build.rs` bakes the same',
  ' * directory into the kernel. Each import is validated + typed by',
  ' * `ThemeDefinitionSchema` at load time — a malformed preset fails the moment',
  ' * this module is imported, not silently.',
  ' */',
  '',
  ...names.map((n) => `import ${identifier(n)} from '../../themes/${n}.json' with { type: 'json' };`),
  '',
  "import { ThemeDefinitionSchema } from '../types/domain.js';",
  "import type { ThemeDefinition } from '../types/domain.js';",
  '',
  'export const THEME_PRESETS: Record<string, ThemeDefinition> = {',
  ...names.map((n) => `  ${key(n)}: ThemeDefinitionSchema.parse(${identifier(n)}),`),
  '};',
  '',
];
writeFileSync(OUT, lines.join('\n'));
console.log(`✓ Generated ${OUT} (${names.length} presets)`);
