/**
 * Event-wire fixtures (Program A, §156, wave A2) — the ONE recorded fixture
 * set every server and client test loads: vitest in `@almadar/runtime` /
 * `@almadar/ui` / `almadar-playground-runtime`, `cargo test` in
 * `orbital-core` / `orbital-server` / `orbital-client` and the native
 * (Android/iOS) shell decoders, the Hono codegen contract test, and `orb
 * verify --server`. Generated by `scripts/generate-event-wire-fixtures.ts`
 * (`pnpm run build:fixtures`, wired into `build`) into
 * `fixtures/events-wire/<case>/{request,response}.json` (+ `stream.json` for
 * `sse-stream`, `live-push.json` for `live-push`), each already validated
 * against the zod schemas at generation time.
 *
 * Node-only (reads from disk with `node:fs`) — this module is exported ONLY
 * from the `@almadar/core/fixtures` subpath, never the main entry, so
 * browser bundles (`@almadar/ui`, the playground client, both of which the
 * root workspace Vite pre-bundles `@almadar/core` through) never pull in
 * `node:fs`. Mirrors the `@almadar/core/mock` subpath precedent for
 * Node/build-only surface area.
 *
 * @packageDocumentation
 */
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { z } from 'zod';

import {
  type OrbitalEventRequest,
  type OrbitalEventResponse,
  type ClientEffectTuple,
  type EmittedEvent,
  type LiveBroadcastItem,
  OrbitalEventRequestSchema,
  OrbitalEventResponseSchema,
  ClientEffectTupleSchema,
  EmittedEventSchema,
  LiveBroadcastItemSchema,
} from './types/bus.js';
import type { JsonValue } from './types/json.js';

/**
 * One SSE stream item, as written by the `POST .../events?stream=true`
 * endpoint's `onPush` calls plus its final write — see `stream.json`'s
 * generator comment (`scripts/generate-event-wire-fixtures.ts`) for the
 * exact source lines. Not part of `types/bus.ts`: the enclosing envelope is
 * `@almadar/server`'s `SSEEvent<T>` transport shape, downstream of core.
 */
export interface SSEStreamItem {
  type: 'event' | 'effect' | 'complete' | 'error';
  data: EmittedEvent | ClientEffectTuple | OrbitalEventResponse | { message: string };
  timestamp: number;
}

/** Zod twin of `SSEStreamItem` — validates at generation AND on load. Input
 *  slot is `object` for the reason given at `BusEventSourceSchema`. */
export const SSEStreamItemSchema: z.ZodType<SSEStreamItem, z.ZodTypeDef, object> = z.union([
  z.object({ type: z.literal('event'), data: EmittedEventSchema, timestamp: z.number() }),
  z.object({ type: z.literal('effect'), data: ClientEffectTupleSchema, timestamp: z.number() }),
  z.object({ type: z.literal('complete'), data: OrbitalEventResponseSchema, timestamp: z.number() }),
  z.object({ type: z.literal('error'), data: z.object({ message: z.string() }), timestamp: z.number() }),
]);

/** One loaded fixture case — the files actually present under `<case>/`. */
export interface EventWireFixture {
  request?: OrbitalEventRequest;
  response?: OrbitalEventResponse;
  stream?: SSEStreamItem[];
  livePush?: LiveBroadcastItem;
}

/**
 * Case names under `fixtures/events-wire/`, in sync with
 * `scripts/generate-event-wire-fixtures.ts` (a generator-time assertion
 * fails the build if the two lists diverge).
 */
export const EVENT_WIRE_FIXTURE_CASES: readonly string[] = [
  'cascade-emitted-events',
  'client-effects-by-trait',
  'effect-results',
  'effect-results-every-kind',
  'guard-rejected',
  'live-push',
  'navigate-1',
  'navigate-2',
  'navigate-3',
  'navigate-back',
  'render-ui-3',
  'render-ui-4',
  'render-ui-5',
  'render-ui-clear',
  'sse-stream',
  'stateless-traits',
];

// `src/fixtures.ts` and its built output `dist/fixtures.js` are both exactly
// one path segment below the package root, so a single `..` resolves
// correctly whether this module runs from source (tests, via tsx/vitest) or
// from the published `dist/`.
const PACKAGE_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

function readJsonIfExists(path: string): JsonValue | undefined {
  try {
    const json: JsonValue = JSON.parse(readFileSync(path, 'utf8'));
    return json;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return undefined;
    throw error;
  }
}

/** Reads `<caseDir>/<file>` and validates it through its schema — the load is
 *  typed by the parse, never by a cast. */
function loadValidated<T>(caseDir: string, file: string, schema: z.ZodType<T, z.ZodTypeDef, object>): T | undefined {
  const json = readJsonIfExists(join(caseDir, file));
  return json === undefined ? undefined : schema.parse(json);
}

/**
 * Loads one case of the recorded event-wire fixture set from disk, relative
 * to the package root (works both from `packages/almadar-core` source and
 * from an installed `node_modules/@almadar/core`, since `fixtures/` ships
 * alongside `dist/` — see `package.json` `files`).
 */
export function loadEventWireFixture(caseName: string): EventWireFixture {
  if (!EVENT_WIRE_FIXTURE_CASES.includes(caseName)) {
    throw new Error(`Unknown event-wire fixture case: "${caseName}". Known cases: ${EVENT_WIRE_FIXTURE_CASES.join(', ')}`);
  }
  const caseDir = join(PACKAGE_ROOT, 'fixtures', 'events-wire', caseName);
  return {
    request: loadValidated(caseDir, 'request.json', OrbitalEventRequestSchema),
    response: loadValidated(caseDir, 'response.json', OrbitalEventResponseSchema),
    stream: loadValidated(caseDir, 'stream.json', z.array(SSEStreamItemSchema)),
    livePush: loadValidated(caseDir, 'live-push.json', LiveBroadcastItemSchema),
  };
}
